apiVersion: v1
kind: Service
metadata:
  name: project4-service
spec:
  type: NodePort
  selector:
    app: project4 
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30001

